version: 0.2

phases:
  install:
    commands:
      - echo Installing Nginx...
      - sudo apt-get update
      - sudo apt-get install -y nginx
  post_build:
    commands:
      - echo Configuring Nginx...
      - sudo cp index.html /var/www/html/
      - sudo service nginx restart

artifacts:
  files:
    - /var/www/html/index.html
